
services:
  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    restart: unless-stopped
    ports:
      - "3420:8000"
    environment:
      - SECRET_KEY=your_secure_secret_key
      - USERNAME=admin
      - PASSWORD=admin
     # Server name for UI (optional, displays in the interface)
     # - DOCKER_HOST_NAME=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro